### ISSUE TITLE
set nocompatible in the LoadWorkspace function reset options to the vim defaults

### ISSUE THREAD

**Issue by santiagohecar** [thaerkh/vim-workspace#4]
I was noticed that some of my vim settings are not apply, checking the code of workspace.vim i see this line `set nocompatible`, this resets some options to the vim defaults, e.g i have `set noshowmode` in my .vimrc but when start vim and type `:set showmode?` to see their value it show me that is on. I do not have much experience with vim but i would suggest you change that line to  `if &compatible | set nocompatible | endif` to solve this problem, i hope any response, this plugin is really util for me, thanks for your great contribution!

**Comment by thaerkh** [comment]
@gohcar I don't believe that would work as intended in the general case (being compatible causes rendering issues). Since this can mess with people's configurations (such as yourself), I've added an option that you can use to stay in compatible mode.

Add the following to get the behaviour you're looking for: `let g:workspace_nocompatible = 0`

Cheers,
Thaer

**Comment by santiagohecar** [comment]
Thanks, this solve the issue.
