### ISSUE TITLE
The cursor moves on 3 symbols right

### ISSUE THREAD

**Issue by backdround** [thaerkh/vim-workspace#9]
Whenever, i do some action, cursor moves on 3 symbols right. There is if autosave is enabled.
neovim/arch

**Comment by uipoet** [comment]
I experienced the same issue and resolved it by specifically disabling the trimming of whitespace on autosave:
`let g:workspace_autosave_untrailspaces = 0`

**Comment by freder** [comment]
same problem here. 

I noticed it happens, when I'm editing `.js` files, but not when I'm editing `.vim` files. – hope that helps.

**Comment by snkshukla** [comment]
For me, earlier cursor was moving 1 char right, now 2 chars right, is there a fix without disabling whitespace trimming? For me it only happens in `.go` files.

**Comment by heratech** [comment]
I think I am getting this issue or a linked issue using Ultisnip. When I have workspace enabled (plugin loaded) the ultisnip goes into the wrong position (2 or 3 spaces to the right of where it should)..

**Comment by maiconviking** [comment]
@uipoet Your solution solved the issue for me. Thank you.

**Comment by wayneforrest** [comment]
@uipoet Your solution works for me too.

**Comment by dustypaws** [comment]
@uipoet Thanks for saving my bacon, mate! :smile:

**Comment by thaerkh** [comment]
I wasn't able to replicate the issue until today - it looks like this happens in some file types (not all) when wrap is enabled by default, on lines that are wrapping (edit: at least that's my first observation, seeing this now in lines with tabs in them), and is likely due to the `virtcol` native method (getting different cursor numbers from what they're supposed to be), which might be a bug in Vim itself. I'll see to resolve the issue within the plugin.

**Comment by thaerkh** [comment]
This should be resolved now with https://github.com/thaerkh/vim-workspace/commit/892a00d199443f09c0a1b93a35c8f9cd1093bb33 (`col` was a more accurate call for this purpose as it was exact byte position)
